export const classicFiltersConfig = [
  {
    fieldKey: "role",
    title: "Current Job Title",
    type: "multi",
    predefinedValues: [
      { label: "CEO/Founders", value: ["8", "35", "103", "1", "195", "9623"] },
      {
        label: "Operations Decions Makers",
        value: ["280", "173", "81", "584", "28"],
      },
      {
        label: "Sales Decision Makers",
        value: [
          "592",
          "48",
          "7778",
          "136",
          "7741",
          "4087",
          "261",
          "19938",
          "1427",
        ],
      },
      {
        label: "HR Decision Makers",
        value: ["5664", "16343", "362", "767", "105", "45"],
      },
      {
        label: "Tech Decision Makers",
        value: [
          "203",
          "153",
          "5134",
          "25884",
          "747",
          "759",
          "163",
          "3177",
          "688",
          "4820",
          "1685",
          "174",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Popular"],
  },
  {
    fieldKey: "industry",
    title: "Industry",
    type: "multi",
    predefinedValues: [
      {
        label: "Technology / IT / Software / Information Services",
        value: [
          "6",
          "4",
          "84",
          "96",
          "1855",
          "3102",
          "3128",
          "1285",
          "3127",
          "3101",
          "3099",
          "3100",
          "3130",
        ],
      },
      {
        label: "Professional Services",
        value: ["1810", "105", "96", "80", "11", "99", "70", "43", "1862"],
      },
      {
        label: "Financial Services",
        value: ["43", "41", "45", "42", "1725", "1737"],
      },
      {
        label: "Manufacturing",
        value: ["25", "53", "112", "135", "15", "54", "23", "55", "17", "1"],
      },
      {
        label: "Education",
        value: ["68", "132", "67", "1999", "105"],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "industry",
    tags: ["Popular"],
  },
  {
    fieldKey: "network_distance",
    title: "Connection Degree",
    type: "multi",
    predefinedValues: [
      { label: "1st", value: 1 },
      { label: "2nd", value: 2 },
      { label: "3rd+", value: 3 },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },

  {
    fieldKey: "location",
    title: "Location",
    type: "multi",
    predefinedValues: [
      { label: "United States", value: "103644278" },
      { label: "North America (US + CA)", value: ["103644278", "101174742"] },
      { label: "United Kingdom", value: "101165590" },
      {
        label: "Western Europe",
        value: [
          "101165590",
          "103883259",
          "100565514",
          "105015875",
          "101282230",
          "104738515",
          "100878084",
          "104042105",
          "101352147",
          "102890719",
          "106693272",
        ],
      },
      {
        label: "Nordics",
        value: [
          "104514075",
          "100456013",
          "105238872",
          "103819153",
          "105117694",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Popular"],
  },
  {
    fieldKey: "company",
    title: "Current Company",
    type: "multi",
    predefinedValues: [
      { label: "Apple", value: "162479" },
      { label: "Microsoft", value: "1035" },
      { label: "IBM", value: "1009" },
      { label: "Oracle", value: "1028" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "past_company",
    title: "Past Company",
    type: "multi",
    predefinedValues: [
      { label: "Apple", value: "162479" },
      { label: "Microsoft", value: "1035" },
      { label: "IBM", value: "1009" },
      { label: "Oracle", value: "1028" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "actively_hiring",
    title: "Actively Hiring",
    type: "multi",
    predefinedValues: [
      { label: "Yes", value: "Yes" },
      { label: "No", value: "No" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Company"],
  },
  {
    fieldKey: "advanced_keywords",
    title: "Keywords",
    type: "text",
    fields: [
       {
        fieldKey: "first_name",
        label: "First Name",
        placeholder: "Enter first name",
      },
      {
        fieldKey: "last_name",
        label: "Last Name",
        placeholder: "Enter last name",
      },
      { fieldKey: "title", label: "Title", placeholder: "Enter job title" },
      { fieldKey: "company", label: "Company", placeholder: "Enter company" },
      { fieldKey: "school", label: "School", placeholder: "Enter school" },
    ],
    tags: ["Personal"],
  },
  {
    fieldKey: "profile_language",
    title: "Profile Language",
    type: "multi",
    predefinedValues: [
      { label: "English", value: "en" },
      { label: "Spanish", value: "es" },
      { label: "Portuguese", value: "pt" },
      { label: "French", value: "fr" },
      { label: "German", value: "de" },
      { label: "Romanian", value: "ro" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "connections_of",
    title: "Connections of",
    type: "multi",
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "connections",
    tags: ["Personal"],
  },
];
