import { predefinedCompaniesList, predefinedIndustriesList, predefinedJobTitlesList, predefinedLanguagesList, predefinedLocationsList } from "../data/filterPredefinedValues";

export const classicFiltersConfig = [
  {
    fieldKey: "role",
    title: "Current Job Title",
    type: "multi",
    predefinedValues: predefinedJobTitlesList,
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Popular"],
  },
  {
    fieldKey: "industry",
    title: "Industry",
    type: "multi",
    predefinedValues: predefinedIndustriesList,
    isAutoSearchEnabled: true,
    filterKey: "industry",
    tags: ["Popular"],
  },
  {
    fieldKey: "network_distance",
    title: "Connection Degree",
    type: "multi",
    predefinedValues: [
      { label: "1st", value: 1 },
      { label: "2nd", value: 2 },
      { label: "3rd+", value: 3 },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },

  {
    fieldKey: "location",
    title: "Location",
    type: "multi",
    predefinedValues: predefinedLocationsList,
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Popular"],
  },
  {
    fieldKey: "company",
    title: "Current Company",
    type: "multi",
    predefinedValues: predefinedCompaniesList,
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "past_company",
    title: "Past Company",
    type: "multi",
    predefinedValues: predefinedCompaniesList,
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "actively_hiring",
    title: "Actively Hiring",
    type: "multi",
    predefinedValues: [
      { label: "Yes", value: "Yes" },
      { label: "No", value: "No" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Company"],
  },
  {
    fieldKey: "advanced_keywords",
    title: "Keywords",
    type: "text",
    fields: [
       {
        fieldKey: "first_name",
        label: "First Name",
        placeholder: "Enter first name",
      },
      {
        fieldKey: "last_name",
        label: "Last Name",
        placeholder: "Enter last name",
      },
      { fieldKey: "title", label: "Title", placeholder: "Enter job title" },
      { fieldKey: "company", label: "Company", placeholder: "Enter company" },
      { fieldKey: "school", label: "School", placeholder: "Enter school" },
    ],
    tags: ["Personal"],
  },
  {
    fieldKey: "profile_language",
    title: "Profile Language",
    type: "multi",
    predefinedValues: predefinedLanguagesList,
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "connections_of",
    title: "Connections of",
    type: "multi",
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "connections",
    tags: ["Personal"],
  },
];
