export const allCountries = [
  { code: "al", name: "Albania" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Armenia" },
  { code: "au", name: "Australia" },
  { code: "at", name: "Austria" },
  { code: "az", name: "Azerbaijan" },
  { code: "bd", name: "Bangladesh" },
  { code: "by", name: "Belarus" },
  { code: "be", name: "Belgium" },
  { code: "bo", name: "Bolivia" },
  { code: "ba", name: "Bosnia And Herzegovina" },
  { code: "br", name: "Brazil" },
  { code: "bg", name: "Bulgaria" },
  { code: "kh", name: "Cambodia" },
  { code: "ca", name: "Canada" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cr", name: "Costa Rica" },
  { code: "hr", name: "Croatia" },
  { code: "cy", name: "Cyprus" },
  { code: "cz", name: "Czech Republic" },
  { code: "dk", name: "Denmark" },
  { code: "do", name: "Dominican Republic" },
  { code: "ec", name: "Ecuador" },
  { code: "eg", name: "Egypt" },
  { code: "ee", name: "Estonia" },
  { code: "fi", name: "Finland" },
  { code: "fr", name: "France" },
  { code: "ge", name: "Georgia" },
  { code: "de", name: "Germany" },
  { code: "gb", name: "Great Britain" },
  { code: "gr", name: "Greece" },
  { code: "gt", name: "Guatemala" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "ie", name: "Ireland" },
  { code: "im", name: "Isle of Man" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italy" },
  { code: "im", name: "Jamaica" },
  { code: "jp", name: "Japan" },
  { code: "jo", name: "Jordan" },
  { code: "kz", name: "Kazakhstan" },
  { code: "ke", name: "Kenya" },
  { code: "kw", name: "Kuwait" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "la", name: "Laos" },
  { code: "lv", name: "Latvia" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "mk", name: "Macedonia" },
  { code: "my", name: "Malaysia" },
  { code: "mt", name: "Malta" },
  { code: "mx", name: "Mexico" },
  { code: "md", name: "Moldova" },
  { code: "ma", name: "Morocco" },
  { code: "nl", name: "Netherlands" },
  { code: "nz", name: "New Zealand" },
  { code: "no", name: "Norway" },
  { code: "om", name: "Oman" },
  { code: "pk", name: "Pakistan" },
  { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "ro", name: "Romania" },
  { code: "ru", name: "Russia" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "rs", name: "Serbia" },
  { code: "sl", name: "Sierra Leone" },
  { code: "sg", name: "Singapore" },
  { code: "si", name: "Slovenia" },
  { code: "za", name: "South Africa" },
  { code: "kr", name: "South Korea" },
  { code: "es", name: "Spain" },
  { code: "lk", name: "Sri Lanka" },
  { code: "se", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  { code: "tw", name: "Taiwan" },
  { code: "tj", name: "Tajikistan" },
  { code: "th", name: "Thailand" },
  { code: "tr", name: "Turkey" },
  { code: "ua", name: "Ukraine" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "United States" },
  { code: "uz", name: "Uzbekistan" },
  { code: "vn", name: "Vietnam" },
];
const allCities = [
  "al-tirana",
  "ar-buenosaires",
  "am-yerevan",
  "au-canberra",
  "au-melbourne",
  "au-sydney",
  "at-vienna",
  "az-baku",
  "bd-dhaka",
  "by-minsk",
  "be-brussels",
  "bo-sucre",
  "ba-sarajevo",
  "br-saopaulo",
  "bg-sofia",
  "kh-phnompenh",
  "ca-toronto",
  "ca-montreal",
  "ca-markham",
  "ca-stoneycreek",
  "ca-vancouver",
  "cn-beijing",
  "cn-shenzhen",
  "cn-shanghai",
  "co-bogota",
  "cr-sanjose",
  "hr-zagreb",
  "cy-nicosia",
  "cz-prague",
  "dk-copenhagen",
  "ec-quito",
  "eg-cairo",
  "ee-tallinn",
  "fk-stanley",
  "fi-helsinki",
  "fr-paris",
  "ge-tbilisi",
  "de-frankfurtammain",
  "de-berlin",
  "gb-london",
  "gr-athens",
  "hk-central",
  "hu-budapest",
  "is-reykjavik",
  "in-delhi",
  "in-mumbai",
  "in-hyderabad",
  "id-jakarta",
  "id-surabaya",
  "iq-baghdad",
  "ie-dublin",
  "im-douglas",
  "il-telaviv",
  "il-haifa",
  "il-jerusalem",
  "it-milan",
  "it-turin",
  "it-rome",
  "jp-tokyo",
  "jo-amman",
  "kz-almaty",
  "ke-nairobi",
  "kw-kuwaitcity",
  "kg-bishkek",
  "la-vientiane",
  "lv-riga",
  "lt-vilnius",
  "lu-luxembourg",
  "mk-skopje",
  "my-kualalumpur",
  "mx-mexicocity",
  "md-chisinau",
  "ms-plymouth",
  "ma-rabat",
  "nl-amsterdam",
  "nl-almerestad",
  "nz-auckland",
  "ng-suleja",
  "no-oslo",
  "om-muscat",
  "pk-islamabad",
  "pe-lima",
  "ph-manila",
  "pl-warsaw",
  "pt-lisbon",
  "ro-bucharest",
  "ru-krasnoyarsk",
  "ru-moscow",
  "sa-riyadh",
  "rs-belgrade",
  "sl-freetown",
  "sg-singapore",
  "sk-bratislava",
  "si-ljubljana",
  "za-centurion",
  "za-gauteng",
  "gs-grytviken",
  "kr-seoul",
  "es-madrid",
  "es-barcelona",
  "lk-colombo",
  "se-stockholm",
  "ch-zurich",
  "tw-taipei",
  "tj-dushanbe",
  "th-bangkok",
  "tn-tunis",
  "tr-ankara",
  "tm-ashgabat",
  "ua-kyiv",
  "ae-dubai",
  "ae-abudhabi",
  "us-newyork",
  "us-casper",
  "us-ashburn",
  "us-siouxfalls",
  "us-losangeles",
  "us-sandiego",
  "us-richmond",
  "us-phoenix",
  "us-boston",
  "us-sanfrancisco",
  "us-atlanta",
  "us-scottsdale",
  "us-charleston",
  "us-charlotte",
  "us-nanuet",
  "us-huntington",
  "us-cleveland",
  "us-newark",
  "us-secaucus",
  "us-miami",
  "us-reston",
  "us-oklahomacity",
  "us-lincoln",
  "us-chicago",
  "us-fresno",
  "us-dallas",
  "us-goodyear",
  "uz-tashkent",
  "vn-hanoi",
];
export const citiesByCountry = allCities.reduce((acc, cityCode) => {
  const [country, city] = cityCode.split("-");
  if (!acc[country]) acc[country] = [];
  acc[country].push(city);
  return acc;
}, {});
