export const allCountries = [
  { code: "ae", name: "United Arab Emirates" },
  { code: "al", name: "Albania" },
  { code: "am", name: "Armenia" },
  { code: "ao", name: "Angola" },
  { code: "ar", name: "Argentina" },
  { code: "at", name: "Austria" },
  { code: "au", name: "Australia" },
  { code: "az", name: "Azerbaijan" },
  { code: "ba", name: "Bosnia And Herzegovina" },
  { code: "bd", name: "Bangladesh" },
  { code: "be", name: "Belgium" },
  { code: "bg", name: "Bulgaria" },
  { code: "bj", name: "Benin" },
  { code: "bo", name: "Bolivia" },
  { code: "br", name: "Brazil" },
  { code: "bw", name: "Botswana" },
  { code: "by", name: "Belarus" },
  { code: "ca", name: "Canada" },
  { code: "ch", name: "Switzerland" },
  { code: "ci", name: "Côte d'Ivoire" },
  { code: "cl", name: "Chile" },
  { code: "cm", name: "Cameroon" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cr", name: "Costa Rica" },
  { code: "cy", name: "Cyprus" },
  { code: "cz", name: "Czech Republic" },
  { code: "de", name: "Germany" },
  { code: "dk", name: "Denmark" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "Dominican Republic" },
  { code: "dz", name: "Algeria" },
  { code: "ec", name: "Ecuador" },
  { code: "ee", name: "Estonia" },
  { code: "eg", name: "Egypt" },
  { code: "es", name: "Spain" },
  { code: "et", name: "Ethiopia" },
  { code: "fi", name: "Finland" },
  { code: "fr", name: "France" },
  { code: "ga", name: "Gabon" },
  { code: "gb", name: "United Kingdom" },
  { code: "ge", name: "Georgia" },
  { code: "gh", name: "Ghana" },
  { code: "gr", name: "Greece" },
  { code: "gt", name: "Guatemala" },
  { code: "gy", name: "Guyana" },
  { code: "hk", name: "Hong Kong" },
  { code: "hn", name: "Honduras" },
  { code: "hr", name: "Croatia" },
  { code: "ht", name: "Haiti" },
  { code: "hu", name: "Hungary" },
  { code: "id", name: "Indonesia" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "in", name: "India" },
  { code: "iq", name: "Iraq" },
  { code: "ir", name: "Iran" },
  { code: "it", name: "Italy" },
  { code: "jm", name: "Jamaica" },
  { code: "jo", name: "Jordan" },
  { code: "jp", name: "Japan" },
  { code: "ke", name: "Kenya" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "kh", name: "Cambodia" },
  { code: "kr", name: "South Korea" },
  { code: "kw", name: "Kuwait" },
  { code: "kz", name: "Kazakhstan" },
  { code: "la", name: "Laos" },
  { code: "lk", name: "Sri Lanka" },
  { code: "ls", name: "Lesotho" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "lv", name: "Latvia" },
  { code: "ma", name: "Morocco" },
  { code: "md", name: "Moldova" },
  { code: "mg", name: "Madagascar" },
  { code: "mk", name: "North Macedonia" },
  { code: "ml", name: "Mali" },
  { code: "mm", name: "Myanmar" },
  { code: "mn", name: "Mongolia" },
  { code: "mo", name: "Macau" },
  { code: "mu", name: "Mauritius" },
  { code: "mx", name: "Mexico" },
  { code: "my", name: "Malaysia" },
  { code: "mz", name: "Mozambique" },
  { code: "na", name: "Namibia" },
  { code: "ng", name: "Nigeria" },
  { code: "ni", name: "Nicaragua" },
  { code: "nl", name: "Netherlands" },
  { code: "no", name: "Norway" },
  { code: "np", name: "Nepal" },
  { code: "nz", name: "New Zealand" },
  { code: "om", name: "Oman" },
  { code: "pa", name: "Panama" },
  { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pk", name: "Pakistan" },
  { code: "pl", name: "Poland" },
  { code: "ps", name: "Palestine" },
  { code: "pt", name: "Portugal" },
  { code: "py", name: "Paraguay" },
  { code: "qa", name: "Qatar" },
  { code: "re", name: "Réunion" },
  { code: "ro", name: "Romania" },
  { code: "rs", name: "Serbia" },
  { code: "ru", name: "Russia" },
  { code: "se", name: "Sweden" },
  { code: "sg", name: "Singapore" },
  { code: "si", name: "Slovenia" },
  { code: "sk", name: "Slovakia" },
  { code: "sn", name: "Senegal" },
  { code: "sr", name: "Suriname" },
  { code: "sv", name: "El Salvador" },
  { code: "sy", name: "Syria" },
  { code: "tg", name: "Togo" },
  { code: "th", name: "Thailand" },
  { code: "tn", name: "Tunisia" },
  { code: "tr", name: "Turkey" },
  { code: "tt", name: "Trinidad and Tobago" },
  { code: "tw", name: "Taiwan" },
  { code: "ua", name: "Ukraine" },
  { code: "ug", name: "Uganda" },
  { code: "us", name: "United States" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistan" },
  { code: "ve", name: "Venezuela" },
  { code: "vn", name: "Vietnam" },
  { code: "za", name: "South Africa" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabwe" },
];

const allCities = [
  { key: "ae-dubai", name: "Dubai" },
  { key: "al-kavaje", name: "Kavaje" },
  { key: "al-tirana", name: "Tirana" },
  { key: "am-yerevan", name: "Yerevan" },
  { key: "ao-luanda", name: "Luanda" },
  { key: "ar-buenos_aires", name: "Buenos Aires" },
  { key: "ar-castelar", name: "Castelar" },
  { key: "ar-cordoba", name: "Cordoba" },
  { key: "ar-jose_c._paz", name: "José C. Paz" },
  { key: "ar-la_plata", name: "La Plata" },
  { key: "ar-mendoza", name: "Mendoza" },
  { key: "ar-rosario", name: "Rosario" },
  { key: "ar-salta", name: "Salta" },
  { key: "ar-san_miguel_de_tucuman", name: "San Miguel de Tucumán" },
  { key: "at-graz", name: "Graz" },
  { key: "at-maria_enzersdorf", name: "Maria Enzersdorf" },
  { key: "at-salzburg", name: "Salzburg" },
  { key: "at-vienna", name: "Vienna" },
  { key: "au-adelaide", name: "Adelaide" },
  { key: "au-brisbane", name: "Brisbane" },
  { key: "au-melbourne", name: "Melbourne" },
  { key: "au-morwell", name: "Morwell" },
  { key: "au-perth", name: "Perth" },
  { key: "au-sydney", name: "Sydney" },
  { key: "az-baku", name: "Baku" },
  { key: "ba-banja_luka", name: "Banja Luka" },
  { key: "ba-sarajevo", name: "Sarajevo" },
  { key: "bd-chattogram", name: "Chattogram" },
  { key: "bd-dhaka", name: "Dhaka" },
  { key: "bd-khulna", name: "Khulna" },
  { key: "be-antwerpen", name: "Antwerpen" },
  { key: "be-brussels", name: "Brussels" },
  { key: "be-gent", name: "Gent" },
  { key: "be-kortrijk", name: "Kortrijk" },
  { key: "be-liege", name: "Liege" },
  { key: "be-lochristi", name: "Lochristi" },
  { key: "be-mechelen", name: "Mechelen" },
  { key: "be-zaventem", name: "Zaventem" },
  { key: "bg-burgas", name: "Burgas" },
  { key: "bg-gabrovo", name: "Gabrovo" },
  { key: "bg-moderno_predgradie", name: "Moderno Predgradie" },
  { key: "bg-plovdiv", name: "Plovdiv" },
  { key: "bg-ruse", name: "Ruse" },
  { key: "bg-samokov", name: "Samokov" },
  { key: "bg-sofia", name: "Sofia" },
  { key: "bg-targovishte", name: "Targovishte" },
  { key: "bg-varna", name: "Varna" },
  { key: "bg-veliko_turnovo", name: "Veliko Turnovo" },
  { key: "bj-cotonou", name: "Cotonou" },
  { key: "bo-cochabamba", name: "Cochabamba" },
  { key: "bo-la_paz", name: "La Paz" },
  { key: "bo-santa_cruz_de_la_sierra", name: "Santa Cruz de la Sierra" },
  { key: "br-alvorada", name: "Alvorada" },
  { key: "br-aracaju", name: "Aracaju" },
  { key: "br-ariquemes", name: "Ariquemes" },
  { key: "br-belem", name: "Belem" },
  { key: "br-belo_horizonte", name: "Belo Horizonte" },
  { key: "br-brasilandia", name: "Brasilandia" },
  { key: "br-brasilia", name: "Brasilia" },
  { key: "br-campinas", name: "Campinas" },
  { key: "br-cuiaba", name: "Cuiaba" },
  { key: "br-curitiba", name: "Curitiba" },
  { key: "br-florianopolis", name: "Florianopolis" },
  { key: "br-fortaleza", name: "Fortaleza" },
  { key: "br-goiania", name: "Goiania" },
  { key: "br-guarulhos", name: "Guarulhos" },
  { key: "br-inhoaiba", name: "Inhoaiba" },
  { key: "br-joao_pessoa", name: "João Pessoa" },
  { key: "br-londrina", name: "Londrina" },
  { key: "br-maceio", name: "Maceio" },
  { key: "br-manaus", name: "Manaus" },
  { key: "br-maringa", name: "Maringa" },
  { key: "br-mesquita", name: "Mesquita" },
  { key: "br-natal", name: "Natal" },
  { key: "br-porto_alegre", name: "Porto Alegre" },
  { key: "br-recife", name: "Recife" },
  { key: "br-ribeirao_preto", name: "Ribeirão Preto" },
  { key: "br-rio_de_janeiro", name: "Rio de Janeiro" },
  { key: "br-salvador", name: "Salvador" },
  { key: "br-santos", name: "Santos" },
  { key: "br-sao_gabriel", name: "São Gabriel" },
  { key: "br-sao_jose_dos_campos", name: "São José dos Campos" },
  { key: "br-sao_paulo", name: "São Paulo" },
  { key: "br-sorocaba", name: "Sorocaba" },
  { key: "br-taquara", name: "Taquara" },
  { key: "br-teresina", name: "Teresina" },
  { key: "br-uberaba", name: "Uberaba" },
  { key: "br-uberlandia", name: "Uberlandia" },
  { key: "br-venda_nova", name: "Venda Nova" },
  { key: "br-vila_velha", name: "Vila Velha" },
  { key: "bw-gaborone", name: "Gaborone" },
  { key: "by-brest", name: "Brest" },
  { key: "by-minsk", name: "Minsk" },
  { key: "by-vitebsk", name: "Vitebsk" },
  { key: "ca-calgary", name: "Calgary" },
  { key: "ca-edmonton", name: "Edmonton" },
  { key: "ca-hamilton", name: "Hamilton" },
  { key: "ca-montreal", name: "Montreal" },
  { key: "ca-ottawa", name: "Ottawa" },
  { key: "ca-pointe-claire", name: "Pointe-Claire" },
  { key: "ca-quebec", name: "Quebec" },
  { key: "ca-saint-laurent", name: "Saint-Laurent" },
  { key: "ca-sherbrooke", name: "Sherbrooke" },
  { key: "ca-toronto", name: "Toronto" },
  { key: "ca-trois-rivieres", name: "Trois-Rivières" },
  { key: "ca-vancouver", name: "Vancouver" },
  { key: "ca-winnipeg", name: "Winnipeg" },
  { key: "ch-bern", name: "Bern" },
  { key: "ch-fribourg", name: "Fribourg" },
  { key: "ch-lausanne", name: "Lausanne" },
  { key: "ch-lugano", name: "Lugano" },
  { key: "ch-sierre", name: "Sierre" },
  { key: "ch-zurich", name: "Zurich" },
  { key: "ci-abidjan", name: "Abidjan" },
  { key: "cl-santiago", name: "Santiago" },
  { key: "cm-douala", name: "Douala" },
  { key: "cn-beijing", name: "Beijing" },
  { key: "cn-chengdu", name: "Chengdu" },
  { key: "cn-chongqing", name: "Chongqing" },
  { key: "cn-dongguan", name: "Dongguan" },
  { key: "cn-fuzhou", name: "Fuzhou" },
  { key: "cn-ganzhou", name: "Ganzhou" },
  { key: "cn-guangzhou", name: "Guangzhou" },
  { key: "cn-hangzhou", name: "Hangzhou" },
  { key: "cn-harbin", name: "Harbin" },
  { key: "cn-hefei", name: "Hefei" },
  { key: "cn-jiaxing", name: "Jiaxing" },
  { key: "cn-jinan", name: "Jinan" },
  { key: "cn-lanzhou", name: "Lanzhou" },
  { key: "cn-nanjing", name: "Nanjing" },
  { key: "cn-nanning", name: "Nanning" },
  { key: "cn-nantong", name: "Nantong" },
  { key: "cn-shanghai", name: "Shanghai" },
  { key: "cn-shenzhen", name: "Shenzhen" },
  { key: "cn-taiyuan", name: "Taiyuan" },
  { key: "cn-wuhan", name: "Wuhan" },
  { key: "co-barranquilla", name: "Barranquilla" },
  { key: "co-bogota", name: "Bogota" },
  { key: "co-bucaramanga", name: "Bucaramanga" },
  { key: "co-cali", name: "Cali" },
  { key: "co-cartagena", name: "Cartagena" },
  { key: "co-cota", name: "Cota" },
  { key: "co-ibague", name: "Ibague" },
  { key: "co-medellin", name: "Medellin" },
  { key: "co-pereira", name: "Pereira" },
  { key: "co-santa_marta", name: "Santa Marta" },
  { key: "cr-san_jose", name: "San José" },
  { key: "cy-limassol", name: "Limassol" },
  { key: "cy-nicosia", name: "Nicosia" },
  { key: "cz-brno", name: "Brno" },
  { key: "cz-ceska", name: "Ceska" },
  { key: "cz-ostrava", name: "Ostrava" },
  { key: "cz-prague", name: "Prague" },
  { key: "cz-usti_nad_labem", name: "Ústí nad Labem" },
  { key: "cz-vranovice", name: "Vranovice" },
  { key: "de-augsburg-lechviertel", name: "Augsburg-Lechviertel" },
  { key: "de-berlin", name: "Berlin" },
  { key: "de-bielefeld", name: "Bielefeld" },
  { key: "de-bonn", name: "Bonn" },
  { key: "de-braunschweig", name: "Braunschweig" },
  { key: "de-bremen", name: "Bremen" },
  { key: "de-dortmund", name: "Dortmund" },
  { key: "de-dresden", name: "Dresden" },
  { key: "de-dusseldorf", name: "Dusseldorf" },
  { key: "de-erfurt", name: "Erfurt" },
  { key: "de-essen", name: "Essen" },
  { key: "de-frankfurt_am_main", name: "Frankfurt am Main" },
  { key: "de-freiburg", name: "Freiburg" },
  { key: "de-freinsheim", name: "Freinsheim" },
  { key: "de-halle_(saale)", name: "Halle (Saale)" },
  { key: "de-hamburg", name: "Hamburg" },
  { key: "de-hanover", name: "Hanover" },
  { key: "de-heidelberg", name: "Heidelberg" },
  { key: "de-isenburg", name: "Isenburg" },
  { key: "de-karlsruhe", name: "Karlsruhe" },
  { key: "de-kerpen", name: "Kerpen" },
  { key: "de-koeln", name: "Koeln" },
  { key: "de-leipzig", name: "Leipzig" },
  { key: "de-magdeburg", name: "Magdeburg" },
  { key: "de-monschau", name: "Monschau" },
  { key: "de-muenster", name: "Muenster" },
  { key: "de-munich", name: "Munich" },
  { key: "de-norderstedt", name: "Norderstedt" },
  { key: "de-nuremberg", name: "Nuremberg" },
  { key: "de-oldenburg", name: "Oldenburg" },
  { key: "de-osnabruck", name: "Osnabruck" },
  { key: "de-potsdam", name: "Potsdam" },
  { key: "de-regensburg", name: "Regensburg" },
  { key: "de-saarbrucken", name: "Saarbrucken" },
  { key: "de-stuttgart", name: "Stuttgart" },
  { key: "de-wald_an_der_alz", name: "Wald an der Alz" },
  { key: "de-wiesbaden", name: "Wiesbaden" },
  { key: "dk-copenhagen", name: "Copenhagen" },
  { key: "dk-sonderborg", name: "Sonderborg" },
  { key: "dk-tranbjerg", name: "Tranbjerg" },
  { key: "dm-roseau", name: "Roseau" },
  { key: "do-la_romana", name: "La Romana" },
  { key: "do-los_llanos", name: "Los Llanos" },
  { key: "do-salvaleon_de_higuey", name: "Salvaleón de Higüey" },
  { key: "do-san_cristobal", name: "San Cristóbal" },
  { key: "do-san_pedro_de_macoris", name: "San Pedro de Macorís" },
  { key: "do-santiago_de_los_caballeros", name: "Santiago de los Caballeros" },
  { key: "do-santo_domingo", name: "Santo Domingo" },
  { key: "dz-algiers", name: "Algiers" },
  { key: "dz-cheraga", name: "Cheraga" },
  { key: "dz-oran", name: "Oran" },
  { key: "ec-guayaquil", name: "Guayaquil" },
  { key: "ec-quito", name: "Quito" },
  { key: "ee-tallinn", name: "Tallinn" },
  { key: "eg-alexandria", name: "Alexandria" },
  { key: "eg-al_khankah", name: "Al Khankah" },
  { key: "eg-cairo", name: "Cairo" },
  { key: "eg-giza", name: "Giza" },
  { key: "es-a_coruna", name: "A Coruña" },
  { key: "es-alicante", name: "Alicante" },
  { key: "es-barcelona", name: "Barcelona" },
  { key: "es-bilbao", name: "Bilbao" },
  { key: "es-granada", name: "Granada" },
  { key: "es-madrid", name: "Madrid" },
  { key: "es-malaga", name: "Malaga" },
  { key: "es-murcia", name: "Murcia" },
  { key: "es-navalcarnero", name: "Navalcarnero" },
  { key: "es-oviedo", name: "Oviedo" },
  { key: "es-pinar_de_chamartin", name: "Pinar de Chamartín" },
  { key: "es-pontevedra", name: "Pontevedra" },
  { key: "es-san_sebastian_de_los_reyes", name: "San Sebastián de los Reyes" },
  { key: "es-sevilla", name: "Sevilla" },
  { key: "es-valencia", name: "Valencia" },
  { key: "es-zaragoza", name: "Zaragoza" },
  { key: "et-addis_ababa", name: "Addis Ababa" },
  { key: "et-dire_dawa", name: "Dire Dawa" },
  { key: "et-nazret", name: "Nazret" },
  { key: "fi-helsinki", name: "Helsinki" },
  { key: "fi-vantaa", name: "Vantaa" },
  { key: "fr-aubervilliers", name: "Aubervilliers" },
  { key: "fr-bethune", name: "Bethune" },
  { key: "fr-bordeaux", name: "Bordeaux" },
  { key: "fr-boulogne-billancourt", name: "Boulogne-Billancourt" },
  { key: "fr-caen", name: "Caen" },
  { key: "fr-cesson-sevigne", name: "Cesson-Sévigné" },
  { key: "fr-champs-sur-marne", name: "Champs-sur-Marne" },
  { key: "fr-compiegne", name: "Compiegne" },
  { key: "fr-issy-les-moulineaux", name: "Issy-les-Moulineaux" },
  { key: "fr-le_kremlin-bicetre", name: "Le Kremlin-Bicêtre" },
  { key: "fr-lyon", name: "Lyon" },
  { key: "fr-marseille", name: "Marseille" },
  { key: "fr-metz", name: "Metz" },
  { key: "fr-meudon", name: "Meudon" },
  { key: "fr-nancy", name: "Nancy" },
  { key: "fr-nanterre", name: "Nanterre" },
  { key: "fr-nantes", name: "Nantes" },
  { key: "fr-nice", name: "Nice" },
  { key: "fr-paris", name: "Paris" },
  { key: "fr-puteaux", name: "Puteaux" },
  { key: "fr-rennes", name: "Rennes" },
  { key: "fr-roubaix", name: "Roubaix" },
  { key: "fr-rouen", name: "Rouen" },
  { key: "fr-saint-denis", name: "Saint-Denis" },
  { key: "fr-strasbourg", name: "Strasbourg" },
  { key: "fr-toulouse", name: "Toulouse" },
  { key: "ga-libreville", name: "Libreville" },
  { key: "gb-adel", name: "Adel" },
  { key: "gb-birmingham", name: "Birmingham" },
  { key: "gb-bradford", name: "Bradford" },
  { key: "gb-bristol", name: "Bristol" },
  { key: "gb-cambridge", name: "Cambridge" },
  { key: "gb-cardiff", name: "Cardiff" },
  { key: "gb-edinburgh", name: "Edinburgh" },
  { key: "gb-exeter", name: "Exeter" },
  { key: "gb-leeds", name: "Leeds" },
  { key: "gb-london", name: "London" },
  { key: "gb-manchester", name: "Manchester" },
  { key: "gb-newcastle_upon_tyne", name: "Newcastle upon Tyne" },
  { key: "gb-nottingham", name: "Nottingham" },
  { key: "gb-poole", name: "Poole" },
  { key: "gb-reading", name: "Reading" },
  { key: "gb-sheffield", name: "Sheffield" },
  { key: "gb-sunbury-on-thames", name: "Sunbury-on-Thames" },
  { key: "gb-warrington", name: "Warrington" },
  { key: "gb-woking", name: "Woking" },
  { key: "gb-york", name: "York" },
  { key: "ge-batumi", name: "Batumi" },
  { key: "ge-meria", name: "Meria" },
  { key: "ge-tbilisi", name: "Tbilisi" },
  { key: "ge-zahesi", name: "Zahesi" },
  { key: "gh-accra", name: "Accra" },
  { key: "gr-athens", name: "Athens" },
  { key: "gr-thessaloniki", name: "Thessaloniki" },
  { key: "gt-guatemala_city", name: "Guatemala City" },
  { key: "gy-george_town", name: "George Town" },
  { key: "hk-hong_kong", name: "Hong Kong" },
  { key: "hn-san_pedro_sula", name: "San Pedro Sula" },
  { key: "hn-tegucigalpa", name: "Tegucigalpa" },
  { key: "hr-rijeka", name: "Rijeka" },
  { key: "hr-split", name: "Split" },
  { key: "hr-zagreb", name: "Zagreb" },
  { key: "ht-port-au-prince", name: "Port-au-Prince" },
  { key: "ht-ti_port-de-paix", name: "Ti Port-de-Paix" },
  { key: "hu-budapest", name: "Budapest" },
  { key: "hu-toeroekbalint", name: "Toeroekbalint" },
  { key: "id-bandarlampung", name: "Bandarlampung" },
  { key: "id-bandung", name: "Bandung" },
  { key: "id-batam", name: "Batam" },
  { key: "id-bekasi", name: "Bekasi" },
  { key: "id-boyolali", name: "Boyolali" },
  { key: "id-cipayung", name: "Cipayung" },
  { key: "id-denpasar", name: "Denpasar" },
  { key: "id-jakarta", name: "Jakarta" },
  { key: "id-jambi", name: "Jambi" },
  { key: "id-madiun", name: "Madiun" },
  { key: "id-makassar", name: "Makassar" },
  { key: "id-malang", name: "Malang" },
  { key: "id-medan", name: "Medan" },
  { key: "id-mergoyoso", name: "Mergoyoso" },
  { key: "id-padalarang", name: "Padalarang" },
  { key: "id-palembang", name: "Palembang" },
  { key: "id-pameungpeuk", name: "Pameungpeuk" },
  { key: "id-ponorogo", name: "Ponorogo" },
  { key: "id-ruteng", name: "Ruteng" },
  { key: "id-semarang", name: "Semarang" },
  { key: "id-serang", name: "Serang" },
  { key: "id-surabaya", name: "Surabaya" },
  { key: "id-surakarta", name: "Surakarta" },
  { key: "id-tangerang", name: "Tangerang" },
  { key: "id-trucuk", name: "Trucuk" },
  { key: "id-ungaran", name: "Ungaran" },
  { key: "id-yogyakarta", name: "Yogyakarta" },
  { key: "ie-dublin", name: "Dublin" },
  { key: "il-haifa", name: "Haifa" },
  { key: "il-petah_tikva", name: "Petah Tikva" },
  { key: "il-tel_aviv", name: "Tel Aviv" },
  { key: "in-ahmedabad", name: "Ahmedabad" },
  { key: "in-bareilly", name: "Bareilly" },
  { key: "in-bengaluru", name: "Bengaluru" },
  { key: "in-bhopal", name: "Bhopal" },
  { key: "in-bhubaneshwar", name: "Bhubaneshwar" },
  { key: "in-chennai", name: "Chennai" },
  { key: "in-chinchvad", name: "Chinchvad" },
  { key: "in-coimbatore", name: "Coimbatore" },
  { key: "in-delhi", name: "Delhi" },
  { key: "in-ernakulam", name: "Ernakulam" },
  { key: "in-faridabad", name: "Faridabad" },
  { key: "in-gurgaon", name: "Gurgaon" },
  { key: "in-hyderabad", name: "Hyderabad" },
  { key: "in-indore", name: "Indore" },
  { key: "in-jabalpur", name: "Jabalpur" },
  { key: "in-jaipur", name: "Jaipur" },
  { key: "in-jalandhar", name: "Jalandhar" },
  { key: "in-kanpur", name: "Kanpur" },
  { key: "in-kolkata", name: "Kolkata" },
  { key: "in-lucknow", name: "Lucknow" },
  { key: "in-mumbai", name: "Mumbai" },
  { key: "in-noida", name: "Noida" },
  { key: "in-patna", name: "Patna" },
  { key: "in-pune", name: "Pune" },
  { key: "in-surat", name: "Surat" },
  { key: "in-thiruvananthapuram", name: "Thiruvananthapuram" },
  { key: "in-thrissur", name: "Thrissur" },
  { key: "in-varanasi", name: "Varanasi" },
  { key: "in-vijayawada", name: "Vijayawada" },
  { key: "iq-baghdad", name: "Baghdad" },
  { key: "iq-erbil", name: "Erbil" },
  { key: "ir-tehran", name: "Tehran" },
  { key: "it-bari", name: "Bari" },
  { key: "it-bergamo", name: "Bergamo" },
  { key: "it-bologna", name: "Bologna" },
  { key: "it-brescia", name: "Brescia" },
  { key: "it-cagliari", name: "Cagliari" },
  { key: "it-catania", name: "Catania" },
  { key: "it-florence", name: "Florence" },
  { key: "it-ivrea", name: "Ivrea" },
  { key: "it-milan", name: "Milan" },
  { key: "it-modena", name: "Modena" },
  { key: "it-naples", name: "Naples" },
  { key: "it-padova", name: "Padova" },
  { key: "it-palermo", name: "Palermo" },
  { key: "it-pisa", name: "Pisa" },
  { key: "it-rome", name: "Rome" },
  { key: "it-torino", name: "Torino" },
  { key: "it-venice", name: "Venice" },
  { key: "it-verona", name: "Verona" },
  { key: "jm-black_river", name: "Black River" },
  { key: "jm-constant_spring", name: "Constant Spring" },
  { key: "jm-half_way_tree", name: "Half Way Tree" },
  { key: "jm-hayes", name: "Hayes" },
  { key: "jm-islington", name: "Islington" },
  { key: "jm-kingston", name: "Kingston" },
  { key: "jm-malvern", name: "Malvern" },
  { key: "jm-mandeville", name: "Mandeville" },
  { key: "jm-mona_heights", name: "Mona Heights" },
  { key: "jm-moneague", name: "Moneague" },
  { key: "jm-montego_bay", name: "Montego Bay" },
  { key: "jm-portmore", name: "Portmore" },
  { key: "jo-amman", name: "Amman" },
  { key: "jp-amagasaki", name: "Amagasaki" },
  { key: "jp-chiba", name: "Chiba" },
  { key: "jp-fukuoka", name: "Fukuoka" },
  { key: "jp-kyoto", name: "Kyoto" },
  { key: "jp-marunouchi", name: "Marunouchi" },
  { key: "jp-nagoya", name: "Nagoya" },
  { key: "jp-osaka", name: "Osaka" },
  { key: "jp-saitama", name: "Saitama" },
  { key: "jp-sendai", name: "Sendai" },
  { key: "jp-tokyo", name: "Tokyo" },
  { key: "jp-yokohama", name: "Yokohama" },
  { key: "ke-athi_river", name: "Athi River" },
  { key: "ke-githurai", name: "Githurai" },
  { key: "ke-kikuyu", name: "Kikuyu" },
  { key: "ke-mombasa", name: "Mombasa" },
  { key: "ke-nairobi", name: "Nairobi" },
  { key: "ke-thika", name: "Thika" },
  { key: "kg-bishkek", name: "Bishkek" },
  { key: "kh-phnom_penh", name: "Phnom Penh" },
  { key: "kr-bucheon", name: "Bucheon" },
  { key: "kr-busan", name: "Busan" },
  { key: "kr-goyang", name: "Goyang" },
  { key: "kr-guri", name: "Guri" },
  { key: "kr-gwangju", name: "Gwangju" },
  { key: "kr-gwangmyeong", name: "Gwangmyeong" },
  { key: "kr-namdong", name: "Namdong" },
  { key: "kr-seongnam", name: "Seongnam" },
  { key: "kr-seoul", name: "Seoul" },
  { key: "kr-suwon", name: "Suwon" },
  { key: "kw-ar_rabiyah", name: "Ar Rabiyah" },
  { key: "kw-kuwait", name: "Kuwait" },
  { key: "kz-almaty", name: "Almaty" },
  { key: "kz-kazakhstan", name: "Kazakhstan" },
  { key: "kz-nur-sultan", name: "Nur-Sultan" },
  { key: "la-muang_hinboun", name: "Muang Hinboun" },
  { key: "la-muang_phon-hong", name: "Muang Phon-Hong" },
  { key: "la-vientiane", name: "Vientiane" },
  { key: "lk-colombo", name: "Colombo" },
  { key: "lk-jaffna", name: "Jaffna" },
  { key: "lk-kandy", name: "Kandy" },
  { key: "lk-kurunegala", name: "Kurunegala" },
  { key: "lk-monaragala", name: "Monaragala" },
  { key: "ls-maseru", name: "Maseru" },
  { key: "lt-kaunas", name: "Kaunas" },
  { key: "lt-klaipeda", name: "Klaipeda" },
  { key: "lt-mazeikiai", name: "Mazeikiai" },
  { key: "lt-vilnius", name: "Vilnius" },
  { key: "lt-visaginas", name: "Visaginas" },
  { key: "lu-luxembourg", name: "Luxembourg" },
  { key: "lv-riga", name: "Riga" },
  { key: "lv-ulbroka", name: "Ulbroka" },
  { key: "ma-agadir", name: "Agadir" },
  { key: "ma-casablanca", name: "Casablanca" },
  { key: "ma-fes", name: "Fes" },
  { key: "ma-kenitra", name: "Kenitra" },
  { key: "ma-marrakesh", name: "Marrakesh" },
  { key: "ma-meknes", name: "Meknes" },
  { key: "ma-rabat", name: "Rabat" },
  { key: "ma-tangier", name: "Tangier" },
  { key: "ma-temara", name: "Temara" },
  { key: "ma-tetouan", name: "Tetouan" },
  { key: "ma-tit_mellil", name: "Tit Mellil" },
  { key: "md-chisinau", name: "Chisinau" },
  { key: "mg-antananarivo", name: "Antananarivo" },
  { key: "mk-skopje", name: "Skopje" },
  { key: "ml-bamako", name: "Bamako" },
  { key: "mm-pyinmana", name: "Pyinmana" },
  { key: "mm-yangon", name: "Yangon" },
  { key: "mn-ulaanbaatar", name: "Ulaanbaatar" },
  { key: "mo-macau", name: "Macau" },
  { key: "mu-curepipe", name: "Curepipe" },
  { key: "mu-port_louis", name: "Port Louis" },
  { key: "mx-ciudad_nezahualcoyotl", name: "Ciudad Nezahualcoyotl" },
  { key: "mx-guadalajara", name: "Guadalajara" },
  { key: "mx-hermosillo", name: "Hermosillo" },
  { key: "mx-mexicali", name: "Mexicali" },
  { key: "mx-mexico_city", name: "Mexico City" },
  { key: "mx-monterrey", name: "Monterrey" },
  { key: "mx-tijuana", name: "Tijuana" },
  { key: "mx-tlalnepantla", name: "Tlalnepantla" },
  { key: "mx-toluca", name: "Toluca" },
  { key: "my-bayan_lepas", name: "Bayan Lepas" },
  { key: "my-bintulu", name: "Bintulu" },
  { key: "my-ipoh", name: "Ipoh" },
  { key: "my-kuala_lumpur", name: "Kuala Lumpur" },
  { key: "my-kuala_terengganu", name: "Kuala Terengganu" },
  { key: "my-kuching", name: "Kuching" },
  { key: "my-kulim", name: "Kulim" },
  { key: "my-melaka", name: "Melaka" },
  { key: "my-petaling", name: "Petaling" },
  { key: "my-sandakan", name: "Sandakan" },
  { key: "my-shah_alam", name: "Shah Alam" },
  { key: "my-skudai", name: "Skudai" },
  { key: "mz-maputo", name: "Maputo" },
  { key: "na-windhoek", name: "Windhoek" },
  { key: "ng-abuja", name: "Abuja" },
  { key: "ng-enugu", name: "Enugu" },
  { key: "ng-lagos", name: "Lagos" },
  { key: "ng-minna", name: "Minna" },
  { key: "ng-opebi", name: "Opebi" },
  { key: "ng-oregun", name: "Oregun" },
  { key: "ng-oshodi", name: "Oshodi" },
  { key: "ng-osogbo", name: "Osogbo" },
  { key: "ni-managua", name: "Managua" },
  { key: "nl-amersfoort", name: "Amersfoort" },
  { key: "nl-amsterdam", name: "Amsterdam" },
  { key: "nl-apeldoorn", name: "Apeldoorn" },
  { key: "nl-diemen", name: "Diemen" },
  { key: "nl-eindhoven", name: "Eindhoven" },
  { key: "nl-enschede", name: "Enschede" },
  { key: "nl-groningen", name: "Groningen" },
  { key: "nl-leeuwarden", name: "Leeuwarden" },
  { key: "nl-oosterhout", name: "Oosterhout" },
  { key: "nl-rotterdam", name: "Rotterdam" },
  { key: "nl-the_hague", name: "The Hague" },
  { key: "nl-utrecht", name: "Utrecht" },
  { key: "nl-zwolle", name: "Zwolle" },
  { key: "no-oslo", name: "Oslo" },
  { key: "no-stavanger", name: "Stavanger" },
  { key: "np-butwal", name: "Butwal" },
  { key: "np-ithari", name: "Ithari" },
  { key: "np-kathmandu", name: "Kathmandu" },
  { key: "np-pokhara", name: "Pokhara" },
  { key: "nz-auckland", name: "Auckland" },
  { key: "om-muscat", name: "Muscat" },
  { key: "pa-panama", name: "Panama" },
  { key: "pe-arequipa", name: "Arequipa" },
  { key: "pe-comas", name: "Comas" },
  { key: "pe-huanuco", name: "Huanuco" },
  { key: "pe-lima", name: "Lima" },
  { key: "pe-trujillo", name: "Trujillo" },
  { key: "ph-angeles_city", name: "Angeles City" },
  { key: "ph-bacolod_city", name: "Bacolod City" },
  { key: "ph-bacoor", name: "Bacoor" },
  { key: "ph-baguio", name: "Baguio" },
  { key: "ph-bulihan", name: "Bulihan" },
  { key: "ph-cagayan_de_oro", name: "Cagayan de Oro" },
  { key: "ph-calamba", name: "Calamba" },
  { key: "ph-cebu_city", name: "Cebu City" },
  { key: "ph-davao_city", name: "Davao City" },
  { key: "ph-diliman", name: "Diliman" },
  { key: "ph-general_santos", name: "General Santos" },
  { key: "ph-iloilo", name: "Iloilo" },
  { key: "ph-makati", name: "Makati" },
  { key: "ph-mambajao", name: "Mambajao" },
  { key: "ph-mandaluyong_city", name: "Mandaluyong City" },
  { key: "ph-manila", name: "Manila" },
  { key: "ph-ormoc", name: "Ormoc" },
  { key: "ph-pakiputan", name: "Pakiputan" },
  { key: "ph-pasig", name: "Pasig" },
  { key: "ph-quiapo", name: "Quiapo" },
  { key: "ph-salcedo", name: "Salcedo" },
  { key: "ph-san_jose_del_monte", name: "San Jose del Monte" },
  { key: "ph-san_mateo", name: "San Mateo" },
  { key: "ph-san_pedro", name: "San Pedro" },
  { key: "ph-san_rafael", name: "San Rafael" },
  { key: "ph-tabaco", name: "Tabaco" },
  { key: "ph-tagbilaran", name: "Tagbilaran" },
  { key: "ph-taguig", name: "Taguig" },
  { key: "ph-valenzuela", name: "Valenzuela" },
  { key: "pk-faisalabad", name: "Faisalabad" },
  { key: "pk-islamabad", name: "Islamabad" },
  { key: "pk-karachi", name: "Karachi" },
  { key: "pk-lahore", name: "Lahore" },
  { key: "pk-pattoki", name: "Pattoki" },
  { key: "pk-peshawar", name: "Peshawar" },
  { key: "pk-rawalpindi", name: "Rawalpindi" },
  { key: "pl-gdansk", name: "Gdansk" },
  { key: "pl-katowice", name: "Katowice" },
  { key: "pl-krakow", name: "Krakow" },
  { key: "pl-lodz", name: "Lodz" },
  { key: "pl-lublin", name: "Lublin" },
  { key: "pl-poznan", name: "Poznan" },
  { key: "pl-szczecin", name: "Szczecin" },
  { key: "pl-warsaw", name: "Warsaw" },
  { key: "pl-wroclaw", name: "Wroclaw" },
  { key: "ps-nablus", name: "Nablus" },
  { key: "pt-almada", name: "Almada" },
  { key: "pt-carnaxide", name: "Carnaxide" },
  { key: "pt-lisbon", name: "Lisbon" },
  { key: "pt-porto", name: "Porto" },
  { key: "py-asuncion", name: "Asuncion" },
  { key: "py-ciudad_del_este", name: "Ciudad del Este" },
  { key: "py-fernando_de_la_mora", name: "Fernando de la Mora" },
  { key: "qa-al_wukayr", name: "Al Wukayr" },
  { key: "qa-ar_rayyan", name: "Ar Rayyan" },
  { key: "qa-doha", name: "Doha" },
  { key: "re-reunion", name: "Reunion" },
  { key: "ro-alba_iulia", name: "Alba Iulia" },
  { key: "ro-bucharest", name: "Bucharest" },
  { key: "ro-caransebes", name: "Caransebes" },
  { key: "ro-chiajna", name: "Chiajna" },
  { key: "ro-cluj-napoca", name: "Cluj-Napoca" },
  { key: "ro-constanta", name: "Constanta" },
  { key: "ro-craiova", name: "Craiova" },
  { key: "ro-galati", name: "Galati" },
  { key: "ro-oradea", name: "Oradea" },
  { key: "ro-pitesti", name: "Pitesti" },
  { key: "ro-sibiu", name: "Sibiu" },
  { key: "ro-targu-mures", name: "Târgu-Mureș" },
  { key: "ro-timisoara", name: "Timisoara" },
  { key: "ro-voluntari", name: "Voluntari" },
  { key: "rs-belgrade", name: "Belgrade" },
  { key: "rs-lazarevac", name: "Lazarevac" },
  { key: "rs-nis", name: "Nis" },
  { key: "rs-novi_pazar", name: "Novi Pazar" },
  { key: "rs-novi_sad", name: "Novi Sad" },
  { key: "rs-pancevo", name: "Pancevo" },
  { key: "rs-pristina", name: "Pristina" },
  { key: "rs-ribnik", name: "Ribnik" },
  { key: "rs-smederevo", name: "Smederevo" },
  { key: "rs-subotica", name: "Subotica" },
  { key: "ru-armavir", name: "Armavir" },
  { key: "ru-barnaul", name: "Barnaul" },
  { key: "ru-belgorod", name: "Belgorod" },
  { key: "ru-bryansk", name: "Bryansk" },
  { key: "ru-cheboksary", name: "Cheboksary" },
  { key: "ru-chelyabinsk", name: "Chelyabinsk" },
  { key: "ru-cherkessk", name: "Cherkessk" },
  { key: "ru-dolgoprudnyy", name: "Dolgoprudnyy" },
  { key: "ru-donetsk", name: "Donetsk" },
  { key: "ru-irkutsk", name: "Irkutsk" },
  { key: "ru-ivanovo", name: "Ivanovo" },
  { key: "ru-izhevsk", name: "Izhevsk" },
  { key: "ru-kaliningrad", name: "Kaliningrad" },
  { key: "ru-kazan", name: "Kazan" },
  { key: "ru-kemerovo", name: "Kemerovo" },
  { key: "ru-khabarovsk", name: "Khabarovsk" },
  { key: "ru-kondratovo", name: "Kondratovo" },
  { key: "ru-kostroma", name: "Kostroma" },
  { key: "ru-krasnodar", name: "Krasnodar" },
  { key: "ru-krasnoyarsk", name: "Krasnoyarsk" },
  { key: "ru-kursk", name: "Kursk" },
  { key: "ru-lenina", name: "Lenina" },
  { key: "ru-lipetsk", name: "Lipetsk" },
  { key: "ru-magnitogorsk", name: "Magnitogorsk" },
  { key: "ru-moscow", name: "Moscow" },
  { key: "ru-murino", name: "Murino" },
  { key: "ru-naberezhnyye_chelny", name: "Naberezhnyye Chelny" },
  { key: "ru-nizhnevartovsk", name: "Nizhnevartovsk" },
  { key: "ru-nizhniy_novgorod", name: "Nizhniy Novgorod" },
  { key: "ru-nizhniy_ufaley", name: "Nizhniy Ufaley" },
  { key: "ru-novokuznetsk", name: "Novokuznetsk" },
  { key: "ru-novosibirsk", name: "Novosibirsk" },
  { key: "ru-omsk", name: "Omsk" },
  { key: "ru-orenburg", name: "Orenburg" },
  { key: "ru-pavlovskiy_posad", name: "Pavlovskiy Posad" },
  { key: "ru-penza", name: "Penza" },
  { key: "ru-perm", name: "Perm" },
  { key: "ru-rostov-na-donu", name: "Rostov-na-Donu" },
  { key: "ru-saint_petersburg", name: "Saint Petersburg" },
  { key: "ru-samara", name: "Samara" },
  { key: "ru-saratov", name: "Saratov" },
  { key: "ru-shuya", name: "Shuya" },
  { key: "ru-smolensk", name: "Smolensk" },
  { key: "ru-surgut", name: "Surgut" },
  { key: "ru-tolyatti", name: "Tolyatti" },
  { key: "ru-tomsk", name: "Tomsk" },
  { key: "ru-tula", name: "Tula" },
  { key: "ru-ufa", name: "Ufa" },
  { key: "ru-velikiy_novgorod", name: "Velikiy Novgorod" },
  { key: "ru-vladivostok", name: "Vladivostok" },
  { key: "ru-volgograd", name: "Volgograd" },
  { key: "ru-voronezh", name: "Voronezh" },
  { key: "ru-yekaterinburg", name: "Yekaterinburg" },
  { key: "ru-yoshkar-ola", name: "Yoshkar-Ola" },
  { key: "ru-zheleznodorozhnyy", name: "Zheleznodorozhnyy" },
  { key: "ru-zlatoust", name: "Zlatoust" },
  { key: "se-goeteborg", name: "Goeteborg" },
  { key: "se-karlskoga", name: "Karlskoga" },
  { key: "se-linkoping", name: "Linkoping" },
  { key: "se-malmoe", name: "Malmoe" },
  { key: "se-stockholm", name: "Stockholm" },
  { key: "sg-singapore", name: "Singapore" },
  { key: "si-ljubljana", name: "Ljubljana" },
  { key: "si-maribor", name: "Maribor" },
  { key: "si-trzin", name: "Trzin" },
  { key: "sk-banska_bystrica", name: "Banska Bystrica" },
  { key: "sk-bratislava", name: "Bratislava" },
  { key: "sn-dakar", name: "Dakar" },
  { key: "sr-paramaribo", name: "Paramaribo" },
  { key: "sv-san_salvador", name: "San Salvador" },
  { key: "sy-damascus", name: "Damascus" },
  { key: "tg-lome", name: "Lome" },
  { key: "th-bangkok", name: "Bangkok" },
  { key: "th-ban_lam_luk_ka", name: "Ban Lam Luk Ka" },
  { key: "th-ban_talat_bueng", name: "Ban Talat Bueng" },
  { key: "th-chiang_mai", name: "Chiang Mai" },
  { key: "th-chon_buri", name: "Chon Buri" },
  { key: "th-hat_yai", name: "Hat Yai" },
  { key: "th-khlong_luang", name: "Khlong Luang" },
  { key: "th-khon_kaen", name: "Khon Kaen" },
  { key: "th-lop_buri", name: "Lop Buri" },
  { key: "th-mueang_nonthaburi", name: "Mueang Nonthaburi" },
  { key: "th-nakhon_ratchasima", name: "Nakhon Ratchasima" },
  { key: "th-pattaya", name: "Pattaya" },
  { key: "th-phra_pradaeng", name: "Phra Pradaeng" },
  { key: "th-phuket", name: "Phuket" },
  { key: "th-rangsit", name: "Rangsit" },
  { key: "th-rayong", name: "Rayong" },
  { key: "th-san_pa_tong", name: "San Pa Tong" },
  { key: "tn-ariana", name: "Ariana" },
  { key: "tn-as_sanad", name: "As Sanad" },
  { key: "tn-ben_arous", name: "Ben Arous" },
  { key: "tn-manouba", name: "Manouba" },
  { key: "tn-sfax", name: "Sfax" },
  { key: "tn-sousse", name: "Sousse" },
  { key: "tn-tunis", name: "Tunis" },
  { key: "tr-adana", name: "Adana" },
  { key: "tr-ankara", name: "Ankara" },
  { key: "tr-bursa", name: "Bursa" },
  { key: "tr-istanbul", name: "Istanbul" },
  { key: "tr-izmir", name: "Izmir" },
  { key: "tr-izmit", name: "Izmit" },
  { key: "tr-mersin", name: "Mersin" },
  { key: "tt-arima", name: "Arima" },
  { key: "tt-chaguanas", name: "Chaguanas" },
  { key: "tt-port_of_spain", name: "Port of Spain" },
  { key: "tt-san_fernando", name: "San Fernando" },
  { key: "tw-banqiao", name: "Banqiao" },
  { key: "tw-changhua", name: "Changhua" },
  { key: "tw-chiayi", name: "Chiayi" },
  { key: "tw-douliu", name: "Douliu" },
  { key: "tw-hsinchu", name: "Hsinchu" },
  { key: "tw-kaohsiung", name: "Kaohsiung" },
  { key: "tw-keelung", name: "Keelung" },
  { key: "tw-nantou", name: "Nantou" },
  { key: "tw-taichung", name: "Taichung" },
  { key: "tw-tainan", name: "Tainan" },
  { key: "tw-taipei", name: "Taipei" },
  { key: "tw-taoyuan", name: "Taoyuan" },
  { key: "tw-yilan", name: "Yilan" },
  { key: "tw-yuanlin", name: "Yuanlin" },
  { key: "ua-dnipro", name: "Dnipro" },
  { key: "ua-kharkiv", name: "Kharkiv" },
  { key: "ua-kiev", name: "Kiev" },
  { key: "ua-lviv", name: "Lviv" },
  { key: "ua-odessa", name: "Odessa" },
  { key: "ua-zaporizhzhya", name: "Zaporizhzhya" },
  { key: "ug-kampala", name: "Kampala" },
  { key: "us-albuquerque", name: "Albuquerque" },
  { key: "us-allen", name: "Allen" },
  { key: "us-allendale", name: "Allendale" },
  { key: "us-arlington", name: "Arlington" },
  { key: "us-ashburn", name: "Ashburn" },
  { key: "us-ashtabula", name: "Ashtabula" },
  { key: "us-atlanta", name: "Atlanta" },
  { key: "us-austin", name: "Austin" },
  { key: "us-baltimore", name: "Baltimore" },
  { key: "us-baton_rouge", name: "Baton Rouge" },
  { key: "us-bellevue", name: "Bellevue" },
  { key: "us-boca_raton", name: "Boca Raton" },
  { key: "us-boston", name: "Boston" },
  { key: "us-bronx", name: "Bronx" },
  { key: "us-brooklyn", name: "Brooklyn" },
  { key: "us-casper", name: "Casper" },
  { key: "us-charleston", name: "Charleston" },
  { key: "us-charlotte", name: "Charlotte" },
  { key: "us-cheney", name: "Cheney" },
  { key: "us-chicago", name: "Chicago" },
  { key: "us-cincinnati", name: "Cincinnati" },
  { key: "us-columbia", name: "Columbia" },
  { key: "us-columbus", name: "Columbus" },
  { key: "us-conroe", name: "Conroe" },
  { key: "us-cupertino", name: "Cupertino" },
  { key: "us-dallas", name: "Dallas" },
  { key: "us-des_moines", name: "Des Moines" },
  { key: "us-detroit", name: "Detroit" },
  { key: "us-el_paso", name: "El Paso" },
  { key: "us-folsom", name: "Folsom" },
  { key: "us-fort_lauderdale", name: "Fort Lauderdale" },
  { key: "us-fort_wayne", name: "Fort Wayne" },
  { key: "us-fort_worth", name: "Fort Worth" },
  { key: "us-franklin", name: "Franklin" },
  { key: "us-gainesville", name: "Gainesville" },
  { key: "us-glendale", name: "Glendale" },
  { key: "us-grand_rapids", name: "Grand Rapids" },
  { key: "us-greenfield", name: "Greenfield" },
  { key: "us-greenville", name: "Greenville" },
  { key: "us-greenwood_village", name: "Greenwood Village" },
  { key: "us-hayward", name: "Hayward" },
  { key: "us-hicksville", name: "Hicksville" },
  { key: "us-highlands_ranch", name: "Highlands Ranch" },
  { key: "us-houston", name: "Houston" },
  { key: "us-indianapolis", name: "Indianapolis" },
  { key: "us-irvine", name: "Irvine" },
  { key: "us-irving", name: "Irving" },
  { key: "us-jackson", name: "Jackson" },
  { key: "us-jacksonville", name: "Jacksonville" },
  { key: "us-jacksonville_beach", name: "Jacksonville Beach" },
  { key: "us-jeffersonville", name: "Jeffersonville" },
  { key: "us-kansas_city", name: "Kansas City" },
  { key: "us-kirkland", name: "Kirkland" },
  { key: "us-knoxville", name: "Knoxville" },
  { key: "us-kremlin", name: "Kremlin" },
  { key: "us-lancaster", name: "Lancaster" },
  { key: "us-las_vegas", name: "Las Vegas" },
  { key: "us-lexington", name: "Lexington" },
  { key: "us-linthicum_heights", name: "Linthicum Heights" },
  { key: "us-livonia", name: "Livonia" },
  { key: "us-los_angeles", name: "Los Angeles" },
  { key: "us-madison", name: "Madison" },
  { key: "us-manhattan", name: "Manhattan" },
  { key: "us-mansfield", name: "Mansfield" },
  { key: "us-mesa", name: "Mesa" },
  { key: "us-miami", name: "Miami" },
  { key: "us-middletown", name: "Middletown" },
  { key: "us-milpitas", name: "Milpitas" },
  { key: "us-minneapolis", name: "Minneapolis" },
  { key: "us-montrose", name: "Montrose" },
  { key: "us-morristown", name: "Morristown" },
  { key: "us-mount_laurel", name: "Mount Laurel" },
  { key: "us-naperville", name: "Naperville" },
  { key: "us-nashville", name: "Nashville" },
  { key: "us-newark", name: "Newark" },
  { key: "us-new_orleans", name: "New Orleans" },
  { key: "us-new_york", name: "New York City" },
  { key: "us-norfolk", name: "Norfolk" },
  { key: "us-oak_lawn", name: "Oak Lawn" },
  { key: "us-oklahoma_city", name: "Oklahoma City" },
  { key: "us-orlando", name: "Orlando" },
  { key: "us-palestine", name: "Palestine" },
  { key: "us-palo_alto", name: "Palo Alto" },
  { key: "us-philadelphia", name: "Philadelphia" },
  { key: "us-phoenix", name: "Phoenix" },
  { key: "us-pittsburgh", name: "Pittsburgh" },
  { key: "us-pomona", name: "Pomona" },
  { key: "us-portland", name: "Portland" },
  { key: "us-providence", name: "Providence" },
  { key: "us-pueblo", name: "Pueblo" },
  { key: "us-raleigh", name: "Raleigh" },
  { key: "us-rancho_santa_margarita", name: "Rancho Santa Margarita" },
  { key: "us-redmond", name: "Redmond" },
  { key: "us-rehoboth_beach", name: "Rehoboth Beach" },
  { key: "us-reston", name: "Reston" },
  { key: "us-richardson", name: "Richardson" },
  { key: "us-richmond", name: "Richmond" },
  { key: "us-rochester", name: "Rochester" },
  { key: "us-rockville", name: "Rockville" },
  { key: "us-sacramento", name: "Sacramento" },
  { key: "us-salt_lake_city", name: "Salt Lake City" },
  { key: "us-san_angelo", name: "San Angelo" },
  { key: "us-san_antonio", name: "San Antonio" },
  { key: "us-san_diego", name: "San Diego" },
  { key: "us-san_francisco", name: "San Francisco" },
  { key: "us-santa_rosa", name: "Santa Rosa" },
  { key: "us-scottsdale", name: "Scottsdale" },
  { key: "us-seattle", name: "Seattle" },
  { key: "us-sheridan", name: "Sheridan" },
  { key: "us-shingle_springs", name: "Shingle Springs" },
  { key: "us-sterling", name: "Sterling" },
  { key: "us-stone_mountain", name: "Stone Mountain" },
  { key: "us-tampa", name: "Tampa" },
  { key: "us-troy", name: "Troy" },
  { key: "us-van_nuys", name: "Van Nuys" },
  { key: "us-walla_walla", name: "Walla Walla" },
  { key: "us-washington", name: "Washington" },
  { key: "us-west_palm_beach", name: "West Palm Beach" },
  { key: "us-wichita", name: "Wichita" },
  { key: "us-wilmington", name: "Wilmington" },
  { key: "uy-montevideo", name: "Montevideo" },
  { key: "uz-salor", name: "Salor" },
  { key: "uz-tashkent", name: "Tashkent" },
  { key: "ve-barquisimeto", name: "Barquisimeto" },
  { key: "ve-cabimas", name: "Cabimas" },
  { key: "ve-caracas", name: "Caracas" },
  { key: "ve-chacao", name: "Chacao" },
  { key: "ve-maracaibo", name: "Maracaibo" },
  { key: "ve-maracay", name: "Maracay" },
  { key: "ve-puerto_la_cruz", name: "Puerto La Cruz" },
  { key: "ve-valera", name: "Valera" },
  { key: "vn-bac_ninh", name: "Bac Ninh" },
  { key: "vn-bien_hoa", name: "Bien Hoa" },
  { key: "vn-buon_ma_thuot", name: "Buon Ma Thuot" },
  { key: "vn-can_duoc", name: "Can Duoc" },
  { key: "vn-can_tho", name: "Can Tho" },
  { key: "vn-co_giang", name: "Co Giang" },
  { key: "vn-da_nang", name: "Da Nang" },
  { key: "vn-dong_thap", name: "Dong Thap" },
  { key: "vn-hai_duong", name: "Hai Duong" },
  { key: "vn-haiphong", name: "Haiphong" },
  { key: "vn-hanoi", name: "Hanoi" },
  { key: "vn-ho_chi_minh_city", name: "Ho Chi Minh City" },
  { key: "vn-hue", name: "Hue" },
  { key: "vn-long_xuyen", name: "Long Xuyen" },
  { key: "vn-nam_dinh", name: "Nam Dinh" },
  { key: "vn-ninh_binh", name: "Ninh Binh" },
  { key: "vn-phu_khuong", name: "Phu Khuong" },
  { key: "vn-son_la", name: "Son La" },
  { key: "vn-thai_binh", name: "Thai Binh" },
  { key: "vn-thai_nguyen", name: "Thai Nguyen" },
  { key: "vn-thang", name: "Thang" },
  { key: "vn-thu_dau_mot", name: "Thu Dau Mot" },
  { key: "vn-uyen_hung", name: "Uyen Hung" },
  { key: "vn-viet_tri", name: "Viet Tri" },
  { key: "vn-vinh", name: "Vinh" },
  { key: "vn-vinh_long", name: "Vinh Long" },
  { key: "vn-vinh_yen", name: "Vinh Yen" },
  { key: "za-cape_town", name: "Cape Town" },
  { key: "za-doornpoort", name: "Doornpoort" },
  { key: "za-johannesburg", name: "Johannesburg" },
  { key: "za-kwadabeka", name: "Kwadabeka" },
  { key: "za-port_elizabeth", name: "Port Elizabeth" },
  { key: "za-pretoria", name: "Pretoria" },
  { key: "zm-kabwe", name: "Kabwe" },
  { key: "zm-lusaka", name: "Lusaka" },
  { key: "zw-harare", name: "Harare" },
];
export const citiesByCountry = allCities.reduce((acc, city) => {
  const [country] = city.key.split("-");
  if (!acc[country]) acc[country] = [];
  acc[country].push(city);
  return acc;
}, {});
