export const planFeatures = {
  basic: {
    general: {
      label: "",
      features: [
        "Dedicated Campaign Success Manager",
        "Omni-Channel Smart Sequences",
        "Email Enrichment and Verification",
        "Automated LinkedIn: Profile Views, Follows, Endorsements, and Post Engagement",
      ],
    },
    more: {
      label: "More Features",
      features: [
        "ChatGPT-4 Template & LinkedIn Post Creation",
        "LinkedIn Post Scheduler",
        "Group, Event, Webinar and \"Who's Viewed Your Profile\" Campaign Generation",
        "A/B Testing",
        "CSV Import Campaigns",
        "Zapier Integration and API Access",
        "CRM integration: Hubspot & Salesforce",
        "Direct Email Integration with Google and Microsoft",
        "Hyperise Integration: Image and GIF Personalization",
        "Monthly Masterclass",
      ],
    },
  },

  professional: {
    includes: {
      label: "Includes Basic, plus;",
      features: [
        "End-to-End AI Campaign Builder",
        "AI Template Map Library",
        "AI-Generated Responses",
        "AI Sentiment Analysis",
        "AI LinkedIn Post Scheduling",
      ],
    },
    basic: {
      label: "Basic Features",
      features: [
        "Dedicated Campaign Success Manager",
        "Omni-Channel Smart Sequences",
        "5000 Email Contacts/Month Included",
        "Email Enrichment and Verification",
        "Automated LinkedIn: Profile Views, Follows, Endorsements, and Post Engagement",
        "ChatGPT-4 Template & LinkedIn Post Creation",
        "LinkedIn Post Scheduler",
        "Group, Event, Webinar and \"Who's Viewed Your Profile\" Campaign Generation",
        "A/B Testing",
        "CSV Import Campaigns",
        "Zapier Integration and API Access",
        "CRM integration: Hubspot & Salesforce",
        "Direct Email Integration with Google and Microsoft",
        "Hyperise Integration: Image and GIF Personalization",
        "Monthly Masterclass",
      ],
    },
  },
  agencyBasic: {
    includes: {
      label: "Includes Basic, plus;",
      features: [
        "End-to-End AI Campaign Builder",
        "AI Template Map Library",
        "AI-Generated Responses",
        "AI Sentiment Analysis",
        "AI LinkedIn Post Scheduling",
      ],
    },
    premiumAgency: {
      label: "Premium Agency Option ($997 one-time fee)",
      features: [
        "Full White-Label",
        "Global Inbox",
        "Global Templates",
        "Global Blacklist",
        "Custom JavaScript Settings",
        "Sub-Agencies",
        "DNS Setup",
        "Deduplication Groupings",
        "Parallel LinkedIn Viewer",
      ],
    },
    basic: {
      label: "Basic Features",
      features: [
        "Dedicated Campaign Success Manager",
        "Omni-Channel Smart Sequences",
        "5000 Email Contacts/Month Included",
        "Email Enrichment and Verification",
        "Automated LinkedIn: Profile Views, Follows, Endorsements, and Post Engagement",
        "ChatGPT-4 Template & LinkedIn Post Creation",
        "LinkedIn Post Scheduler",
        "Group, Event, Webinar and \"Who's Viewed Your Profile\" Campaign Generation",
        "A/B Testing",
        "CSV Import Campaigns",
        "Zapier Integration and API Access",
        "CRM integration: Hubspot & Salesforce",
        "Direct Email Integration with Google and Microsoft",
        "Hyperise Integration: Image and GIF Personalization",
        "Monthly Masterclass",
      ],
    },
  },

  agencyPro: {
    includes: {
      label: "Includes Basic, plus;",
      features: [
        "End-to-End AI Campaign Builder",
        "AI Template Map Library",
        "AI-Generated Responses",
        "AI Sentiment Analysis",
        "AI LinkedIn Post Scheduling",
        "AI Customer Personas",
      ],
    },
    premiumAgency: {
      label: "Premium Agency Option ($997 one-time fee)",
      features: [
        "Full White-Label",
        "Global Inbox",
        "Global Templates",
        "Global Blacklist",
        "Custom JavaScript Settings",
        "Sub-Agencies",
        "DNS Setup",
        "API Access",
        "Deduplication Groupings",
        "Parallel LinkedIn Viewer",
      ],
    },
    basic: {
      label: "Basic Features",
      features: [
        "ChatGPT-4 Template & LinkedIn Post Creation",
        "LinkedIn Post Scheduler",
        "Group, Event, Webinar and \"Who's Viewed Your Profile\" Campaign Generation",
        "A/B Testing",
        "CSV Import Campaigns",
        "Zapier Integration and API Access",
        "CRM integration: Hubspot & Salesforce",
        "Direct Email Integration with Google and Microsoft",
        "Hyperise Integration: Image and GIF Personalization",
        "Monthly Masterclass",
      ],
    },
    pro: {
      label: "Pro",
      features: [
        "End-to-End AI Campaign Builder",
        "AI Template Map Library",
        "AI-Generated Responses",
        "AI Sentiment Analysis",
        "AI LinkedIn Post Scheduling",
        "AI Customer Personas",
      ],
    },
  },
};
