export const sampleRecipients = [
  { name: "Robert Dan", company: "NBS" },
  { name: "John Doe", company: "Systems IT" },
  { name: "Danial Doe", company: "Remotebase LTD" },
  { name: "John Bradman", company: "Afiniti" },
  { name: "Dave Loren", company: "Star Light LTD" },
];

// Per-recipient variable maps (one entry per recipient/tab)
export const sampleVariablesList = [
  {
    "{{FIRST_NAME}}": "Robert",
    "{{LAST_NAME}}": "Dan",
    "{{INDUSTRY}}": "Technology",
    "{{COMPANY}}": "NBS",
    "{{ROLE}}": "Sales Manager",
    "{{LOCATION}}": "London",
    "{{CUSTOM_FIELD_1}}": "Value 1",
    "{{CUSTOM_FIELD_2}}": "Value 2",
    "{{CUSTOM_FIELD_3}}": "Value 3",
  },
  {
    "{{FIRST_NAME}}": "John",
    "{{LAST_NAME}}": "Doe",
    "{{INDUSTRY}}": "IT Services",
    "{{COMPANY}}": "Systems IT",
    "{{ROLE}}": "Infrastructure Lead",
    "{{LOCATION}}": "Manchester",
    "{{CUSTOM_FIELD_1}}": "Alpha",
    "{{CUSTOM_FIELD_2}}": "Beta",
    "{{CUSTOM_FIELD_3}}": "Gamma",
  },
  {
    "{{FIRST_NAME}}": "Danial",
    "{{LAST_NAME}}": "Doe",
    "{{INDUSTRY}}": "Software",
    "{{COMPANY}}": "Remotebase LTD",
    "{{ROLE}}": "Frontend Engineer",
    "{{LOCATION}}": "Remote",
    "{{CUSTOM_FIELD_1}}": "One",
    "{{CUSTOM_FIELD_2}}": "Two",
    "{{CUSTOM_FIELD_3}}": "Three",
  },
  {
    "{{FIRST_NAME}}": "John",
    "{{LAST_NAME}}": "Bradman",
    "{{INDUSTRY}}": "Consulting",
    "{{COMPANY}}": "Afiniti",
    "{{ROLE}}": "Account Manager",
    "{{LOCATION}}": "Bristol",
    "{{CUSTOM_FIELD_1}}": "X",
    "{{CUSTOM_FIELD_2}}": "Y",
    "{{CUSTOM_FIELD_3}}": "Z",
  },
  {
    "{{FIRST_NAME}}": "Dave",
    "{{LAST_NAME}}": "Loren",
    "{{INDUSTRY}}": "Retail",
    "{{COMPANY}}": "Star Light LTD",
    "{{ROLE}}": "Head of Sales",
    "{{LOCATION}}": "Leeds",
    "{{CUSTOM_FIELD_1}}": "Red",
    "{{CUSTOM_FIELD_2}}": "Green",
    "{{CUSTOM_FIELD_3}}": "Blue",
  },
];