export const salesNavigatorFiltersConfig = [
  {
    fieldKey: "role",
    title: "Current Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "CEO/Founders", value: "1" },
      { label: "Sales Decision Makers", value: "2" },
      { label: "HR Decision Makers", value: "3" },
      { label: "Tech Decision Makers", value: "4" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Popular"],
  },
  {
    fieldKey: "industry",
    title: "Industry",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Technology, Information and Media", value: "tim" },
      { label: "Technology, Information and Internet", value: "tii" },
      { label: "Professional Services", value: "prof-services" },
      { label: "Software Development", value: "software-dev" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "industry",
    tags: ["Popular"],
  },
  {
    fieldKey: "company_headcount",
    title: "Company Headcount",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "1-10", value: { min: 1, max: 10 } },
      { label: "51-200", value: { min: 51, max: 200 } },
      { label: "501 - 1000", value: { min: 501, max: 1000 } },
      { label: "1001-5000", value: { min: 1001, max: 5000 } },
      { label: "5001-10,000", value: { min: 5001, max: 10000 } },
      { label: "10,000+", value: { min: 10001 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "location",
    title: "Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Egypt", value: "egypt" },
      { label: "United State", value: "united-states" },
      { label: "London Area, United Kingdom", value: "london-uk" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Popular"],
  },
  {
    fieldKey: "network_distance",
    title: "Connection Degree",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "1st", value: 1 },
      { label: "2nd", value: 2 },
      { label: "3rd+", value: 3 },
      { label: "Group", value: "GROUP" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "posted_on_linkedin",
    title: "Posted on LinkedIn",
    type: "boolean",
    tags: ["Popular"],
  },
  {
    fieldKey: "company",
    title: "Current Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Zopto", value: "zopto" },
      { label: "Zeekeo", value: "zeekeo" },
      { label: "Pimula", value: "pimula" },
      { label: "IBM", value: "ibm" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "past_company",
    title: "Past Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Zopto", value: "zopto" },
      { label: "Zeekeo", value: "zeekeo" },
      { label: "Pimula", value: "pimula" },
      { label: "IBM", value: "ibm" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "company_type",
    title: "Company Type",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Public Company", value: "public_company" },
      { label: "Privately Held", value: "privately_held" },
      { label: "Non profit", value: "non_profit" },
      { label: "Educational Institution", value: "educational_institution" },
      { label: "Partnership", value: "partnership" },
      { label: "Self Employed", value: "self_employed" },
      { label: "Self Owned", value: "self_owned" },
      { label: "Government Agency", value: "government_agency" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Company"],
  },
  {
    fieldKey: "company_location",
    title: "Company Headquarters Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Egypt", value: "egypt" },
      { label: "United State", value: "united-states" },
      { label: "London Area, United Kingdom", value: "london-uk" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Company"],
  },
  {
    fieldKey: "function",
    title: "Function",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Software Development", value: "software-dev" },
      { label: "Database Development", value: "db-dev" },
      { label: "SaaS Development", value: "saas-dev" },
      { label: "Marketing", value: "marketing" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_function",
    tags: ["Role"],
  },
  {
    fieldKey: "seniority",
    title: "Seniority Level",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Owner/Partner", value: "owner/partner" },
      { label: "CXO", value: "cxo" },
      { label: "Vice President", value: "vice_president" },
      { label: "Director", value: "director" },
      { label: "Experienced Manager", value: "experienced_manager" },
      { label: "Eentry Level Manager", value: "entry_level_manager" },
      { label: "Entry Level", value: "entry_level" },
      { label: "Senior", value: "senior" },
      { label: "Strategic", value: "strategic" },
      { label: "In Training", value: "in_training" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "past_role",
    title: "Past Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "CEO/Founders", value: "1" },
      { label: "Sales Decision Makers", value: "2" },
      { label: "HR Decision Makers", value: "3" },
      { label: "Tech Decision Makers", value: "4" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_role",
    title: "Years in Current Position",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_company",
    title: "Years in Current Company",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "first_name",
    title: "First Name",
    placeholder: "Enter first name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "last_name",
    title: "Last Name",
    placeholder: "Enter last name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "profile_language",
    title: "Profile Language",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "English", value: "en" },
      { label: "French", value: "fr" },
      { label: "Spanish", value: "sp" },
      { label: "Romanian", value: "ro" },
      { label: "Others", value: "others" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "tenure",
    title: "Years of Experience",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "groups",
    title: "Groups",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Group 1", value: "1" },
      { label: "Group 2", value: "2" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "groups",
    tags: ["Personal"],
  },
  {
    fieldKey: "school",
    title: "School",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Alexandria University", value: "1" },
      {
        label: "National Institute of Computer and Emerging Services",
        value: "2",
      },
      { label: "Information Technology Institute (ITI)", value: "3" },
      { label: "Damascus University", value: "4" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "school",
    tags: ["Personal"],
  },
  {
    fieldKey: "changed_jobs",
    title: "Changed Jobs Recently",
    type: "boolean",
    tags: ["Personal"],
  },
  {
    fieldKey: "following_your_company",
    title: "Following Your Company",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "viewed_your_profile_recently",
    title: "Viewed Your Profile Recently",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "connections_of",
    title: "Connections of",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Shailendar Sharma", value: "shailendar-sharma" },
      { label: "Sagor Chowdary", value: "sagor" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "connections",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "past_colleage",
    title: "Past Colleagues",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "shared_experiences",
    title: "Shared Experiences",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "persona",
    title: "Persona",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Default Persona", value: "default" },
      { label: "CXO", value: "cxo" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "persona",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "account_lists",
    title: "Account Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Account List 1", value: "1" },
      {
        label: "Account List 2",
        value: "2",
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "account_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "lead_lists",
    title: "Lead Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Lead List 1", value: "1" },
      {
        label: "Lead List 2",
        value: "2",
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "lead_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_leads",
    title: "Include People in CRM",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "messaged_recently",
    title: "Include People You Interacted With",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_accounts",
    title: "Include Saved Lists",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
];
