export const salesNavigatorFiltersConfig = [
  {
    fieldKey: "role",
    title: "Current Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "CEO/Founders", value: ["8", "35", "103", "1", "195", "9623"] },
      {
        label: "Operations Decions Makers",
        value: ["280", "173", "81", "584", "28"],
      },
      {
        label: "Sales Decision Makers",
        value: [
          "592",
          "48",
          "7778",
          "136",
          "7741",
          "4087",
          "261",
          "19938",
          "1427",
        ],
      },
      {
        label: "HR Decision Makers",
        value: ["5664", "16343", "362", "767", "105", "45"],
      },
      {
        label: "Tech Decision Makers",
        value: [
          "203",
          "153",
          "5134",
          "25884",
          "747",
          "759",
          "163",
          "3177",
          "688",
          "4820",
          "1685",
          "174",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Popular"],
  },
  {
    fieldKey: "industry",
    title: "Industry",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      {
        label: "Technology / IT / Software / Information Services",
        value: [
          "6",
          "4",
          "84",
          "96",
          "1855",
          "3102",
          "3128",
          "1285",
          "3127",
          "3101",
          "3099",
          "3100",
          "3130",
        ],
      },
      {
        label: "Professional Services",
        value: ["1810", "105", "96", "80", "11", "99", "70", "43", "1862"],
      },
      {
        label: "Financial Services",
        value: ["43", "41", "45", "42", "1725", "1737"],
      },
      {
        label: "Manufacturing",
        value: ["25", "53", "112", "135", "15", "54", "23", "55", "17", "1"],
      },
      {
        label: "Education",
        value: ["68", "132", "67", "1999", "105"],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "industry",
    tags: ["Popular"],
  },
  {
    fieldKey: "company_headcount",
    title: "Company Headcount",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "1-10", value: { min: 1, max: 10 } },
      { label: "51-200", value: { min: 51, max: 200 } },
      { label: "501 - 1000", value: { min: 501, max: 1000 } },
      { label: "1001-5000", value: { min: 1001, max: 5000 } },
      { label: "5001-10,000", value: { min: 5001, max: 10000 } },
      { label: "10,000+", value: { min: 10001 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "location",
    title: "Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "United States", value: "103644278" },
      { label: "North America (US + CA)", value: ["103644278", "101174742"] },
      { label: "United Kingdom", value: "101165590" },
      {
        label: "Western Europe",
        value: [
          "101165590",
          "103883259",
          "100565514",
          "105015875",
          "101282230",
          "104738515",
          "100878084",
          "104042105",
          "101352147",
          "102890719",
          "106693272",
        ],
      },
      {
        label: "Nordics",
        value: [
          "104514075",
          "100456013",
          "105238872",
          "103819153",
          "105117694",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Popular"],
  },
  {
    fieldKey: "network_distance",
    title: "Connection Degree",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "1st", value: 1 },
      { label: "2nd", value: 2 },
      { label: "3rd+", value: 3 },
      { label: "Group", value: "GROUP" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "posted_on_linkedin",
    title: "Posted on LinkedIn",
    type: "boolean",
    tags: ["Popular"],
  },
  {
    fieldKey: "company",
    title: "Current Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Apple", value: "162479" },
      { label: "Microsoft", value: "1035" },
      { label: "IBM", value: "1009" },
      { label: "Oracle", value: "1028" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "past_company",
    title: "Past Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Apple", value: "162479" },
      { label: "Microsoft", value: "1035" },
      { label: "IBM", value: "1009" },
      { label: "Oracle", value: "1028" },
    ],
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "company_type",
    title: "Company Type",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Public Company", value: "C" },
      { label: "Privately Held", value: "P" },
      { label: "Non Profit", value: "N" },
      { label: "Educational Institution", value: "D" },
      { label: "Self Employed", value: "E" },
      { label: "Partnership", value: "S" },
      { label: "Self Owned", value: "O" },
      { label: "Government Agency", value: "G" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Company"],
  },
  {
    fieldKey: "company_location",
    title: "Company Headquarters Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "United States", value: "103644278" },
      { label: "North America (US + CA)", value: ["103644278", "101174742"] },
      { label: "United Kingdom", value: "101165590" },
      {
        label: "Western Europe",
        value: [
          "101165590",
          "103883259",
          "100565514",
          "105015875",
          "101282230",
          "104738515",
          "100878084",
          "104042105",
          "101352147",
          "102890719",
          "106693272",
        ],
      },
      {
        label: "Nordics",
        value: [
          "104514075",
          "100456013",
          "105238872",
          "103819153",
          "105117694",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Company"],
  },
  {
    fieldKey: "function",
    title: "Function",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      {
        label: "Business and Strategy",
        value: ["bd", "cnsl", "prdm", "prch", "prjm"],
      },
      {
        label: "Corporate and Administrative",
        value: ["acct", "adm", "fin", "hr", "lgl", "qa"],
      },
      { label: "Technical and Creative", value: ["eng", "it", "art", "rsch"] },
      { label: "Customer and Commercial", value: ["mrkt", "sale", "cust"] },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_function",
    tags: ["Role"],
  },
  {
    fieldKey: "seniority",
    title: "Seniority Level",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "Owner / Partner", value: "320" },
      { label: "Entry Level", value: "110" },
      { label: "CXO", value: "310" },
      { label: "Vice President", value: "300" },
      { label: "Experienced Manager", value: "210" },
      { label: "Director", value: "220" },
      { label: "Entry Level Manager", value: "200" },
      { label: "Strategic", value: "130" },
      { label: "In Training", value: "100" },
      { label: "Senior", value: "120" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "past_role",
    title: "Past Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: [
      { label: "CEO/Founders", value: ["8", "35", "103", "1", "195", "9623"] },
      {
        label: "Operations Decions Makers",
        value: ["280", "173", "81", "584", "28"],
      },
      {
        label: "Sales Decision Makers",
        value: [
          "592",
          "48",
          "7778",
          "136",
          "7741",
          "4087",
          "261",
          "19938",
          "1427",
        ],
      },
      {
        label: "HR Decision Makers",
        value: ["5664", "16343", "362", "767", "105", "45"],
      },
      {
        label: "Tech Decision Makers",
        value: [
          "203",
          "153",
          "5134",
          "25884",
          "747",
          "759",
          "163",
          "3177",
          "688",
          "4820",
          "1685",
          "174",
        ],
      },
    ],
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_role",
    title: "Years in Current Position",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_company",
    title: "Years in Current Company",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "first_name",
    title: "First Name",
    placeholder: "Enter first name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "last_name",
    title: "Last Name",
    placeholder: "Enter last name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "profile_language",
    title: "Profile Language",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "English", value: "en" },
      { label: "Spanish", value: "es" },
      { label: "Portuguese", value: "pt" },
      { label: "French", value: "fr" },
      { label: "German", value: "de" },
      { label: "Romanian", value: "ro" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "tenure",
    title: "Years of Experience",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "Less than 1 year", value: { min: 0, max: 1 } },
      { label: "1 to 2 Years", value: { min: 1, max: 2 } },
      { label: "3 to 5 Years", value: { min: 3, max: 5 } },
      { label: "6 to 10 Years", value: { min: 6, max: 10 } },
      { label: "More than 10 Years", value: { min: 10, max: 0 } },
    ],
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "groups",
    title: "Groups",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "groups",
    tags: ["Personal"],
  },
  {
    fieldKey: "school",
    title: "School",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "school",
    tags: ["Personal"],
  },
  {
    fieldKey: "changed_jobs",
    title: "Changed Jobs Recently",
    type: "boolean",
    tags: ["Personal"],
  },
  {
    fieldKey: "following_your_company",
    title: "Following Your Company",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "viewed_your_profile_recently",
    title: "Viewed Your Profile Recently",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "connections_of",
    title: "Connections of",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "connections",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "past_colleage",
    title: "Past Colleagues",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "shared_experiences",
    title: "Shared Experiences",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "persona",
    title: "Persona",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "persona",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "account_lists",
    title: "Account Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "account_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "lead_lists",
    title: "Lead Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "lead_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_leads",
    title: "Include People in CRM",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "messaged_recently",
    title: "Include People You Interacted With",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_accounts",
    title: "Include Saved Lists",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
];
