import { pre } from "framer-motion/client";
import {
  predefinedCompaniesList,
  predefinedCompanyHeadcountsList,
  predefinedCompanyTypesList,
  predefinedFunctionsList,
  predefinedIndustriesList,
  predefinedJobTitlesList,
  predefinedLanguagesList,
  predefinedLocationsList,
  predefinedSenioritiesList,
  predefinedYearsOfExperienceList,
} from "../data/filterPredefinedValues";

export const salesNavigatorFiltersConfig = [
  {
    fieldKey: "role",
    title: "Current Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedJobTitlesList,
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Popular"],
  },
  {
    fieldKey: "industry",
    title: "Industry",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedIndustriesList,
    isAutoSearchEnabled: true,
    filterKey: "industry",
    tags: ["Popular"],
  },
  {
    fieldKey: "company_headcount",
    title: "Company Headcount",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedCompanyHeadcountsList,
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "location",
    title: "Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedLocationsList,
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Popular"],
  },
  {
    fieldKey: "network_distance",
    title: "Connection Degree",
    type: "multi",
    includeExclude: false,
    predefinedValues: [
      { label: "1st", value: 1 },
      { label: "2nd", value: 2 },
      { label: "3rd+", value: 3 },
      { label: "Group", value: "GROUP" },
    ],
    isAutoSearchEnabled: false,
    tags: ["Popular"],
  },
  {
    fieldKey: "posted_on_linkedin",
    title: "Posted on LinkedIn",
    type: "boolean",
    tags: ["Popular"],
  },
  {
    fieldKey: "keywords",
    title: "Keywords",
    placeholder: "Enter keyword",
    type: "text",
    tags: ["Popular"],
  },
  {
    fieldKey: "company",
    title: "Current Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedCompaniesList,
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "past_company",
    title: "Past Company",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedCompaniesList,
    isAutoSearchEnabled: true,
    filterKey: "company",
    tags: ["Company"],
  },
  {
    fieldKey: "company_type",
    title: "Company Type",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedCompanyTypesList,
    isAutoSearchEnabled: false,
    tags: ["Company"],
  },
  {
    fieldKey: "company_location",
    title: "Company Headquarters Location",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedLocationsList,
    isAutoSearchEnabled: true,
    filterKey: "location",
    tags: ["Company"],
  },
  {
    fieldKey: "function",
    title: "Function",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedFunctionsList,
    isAutoSearchEnabled: true,
    filterKey: "job_function",
    tags: ["Role"],
  },
  {
    fieldKey: "seniority",
    title: "Seniority Level",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedSenioritiesList,
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "past_role",
    title: "Past Job Title",
    type: "multi",
    includeExclude: true,
    predefinedValues: predefinedJobTitlesList,
    isAutoSearchEnabled: true,
    filterKey: "job_title",
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_role",
    title: "Years in Current Position",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedYearsOfExperienceList,
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "tenure_at_company",
    title: "Years in Current Company",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedYearsOfExperienceList,
    isAutoSearchEnabled: false,
    tags: ["Role"],
  },
  {
    fieldKey: "first_name",
    title: "First Name",
    placeholder: "Enter first name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "last_name",
    title: "Last Name",
    placeholder: "Enter last name",
    type: "text",
    tags: ["Personal"],
  },
  {
    fieldKey: "profile_language",
    title: "Profile Language",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedLanguagesList,
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "tenure",
    title: "Years of Experience",
    type: "multi",
    includeExclude: false,
    predefinedValues: predefinedYearsOfExperienceList,
    isAutoSearchEnabled: false,
    tags: ["Personal"],
  },
  {
    fieldKey: "groups",
    title: "Groups",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "groups",
    tags: ["Personal"],
  },
  {
    fieldKey: "school",
    title: "School",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "school",
    tags: ["Personal"],
  },
  {
    fieldKey: "changed_jobs",
    title: "Changed Jobs Recently",
    type: "boolean",
    tags: ["Personal"],
  },
  {
    fieldKey: "following_your_company",
    title: "Following Your Company",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "viewed_your_profile_recently",
    title: "Viewed Your Profile Recently",
    type: "boolean",
    tags: ["Buyer Intent"],
  },
  {
    fieldKey: "connections_of",
    title: "Connections of",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "connections",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "past_colleage",
    title: "Past Colleagues",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "shared_experiences",
    title: "Shared Experiences",
    type: "boolean",
    tags: ["Best Path in"],
  },
  {
    fieldKey: "persona",
    title: "Persona",
    type: "multi",
    includeExclude: false,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "persona",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "account_lists",
    title: "Account Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "account_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "lead_lists",
    title: "Lead Lists",
    type: "multi",
    includeExclude: true,
    predefinedValues: [],
    isAutoSearchEnabled: true,
    filterKey: "lead_lists",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_leads",
    title: "Include People in CRM",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "messaged_recently",
    title: "Include People You Interacted With",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
  {
    fieldKey: "include_saved_accounts",
    title: "Include Saved Lists",
    type: "boolean",
    tags: ["Sales Navigator Workflow"],
  },
];
